server:
  port: 8097

spring.jpa:
  hibernate.ddl-auto: none

spring.datasource:
  url: jdbc:h2:tcp://localhost/~/test
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.mvc.view:
  prefix: /
  suffix: .jsp